// Fit limits: how much text each diagram family can lay out without clipping, overprinting or leaving the canvas.
// The numbers live in fit-limits.mjs (generated by `node scripts/render-quality-gate.mjs --tune`); this module
// measures text the way the layouts do and turns a violation into an actionable error.
import { FIT_LIMITS } from './fit-limits.mjs';

export const PRESETS = {
  'doc-wide': { width: 1200, height: 700 },
  'slide-16x9': { width: 1600, height: 900 },
  'social-square': { width: 1080, height: 1080 },
  fit: { width: 1200, height: 800 },
};
export const marginOf = (preset) => (preset === 'slide-16x9' ? 84 : 64);

/**
 * Greedy word wrap measured in visual cells. A line may also break after "/", "-" or "·" inside a word, and a piece
 * longer than a line is broken at the line width.
 */
export function wrapAll(text, maxChars) {
  const pieces = [];
  for (const word of String(text).trim().split(/\s+/)) {
    word.split(/(?<=[/\-\u00b7])(?=.)/u).forEach((part, index) => {
      if (cells(part) <= maxChars) { pieces.push({ part, glue: index > 0 }); return; }
      let piece = '';
      let first = true;
      for (const ch of part) {
        if (cells(piece) + cells(ch) > maxChars) { pieces.push({ part: piece, glue: index > 0 || !first }); piece = ''; first = false; }
        piece += ch;
      }
      pieces.push({ part: piece, glue: index > 0 || !first });
    });
  }
  const lines = [];
  let current = '';
  for (const { part, glue } of pieces) {
    const next = current ? `${current}${glue ? '' : ' '}${part}` : part;
    if (cells(next) <= maxChars || !current) current = next;
    else {
      lines.push(current);
      current = part;
    }
  }
  if (current) lines.push(current);
  return lines;
}

/**
 * Header geometry shared by the renderer and the limits: a title shrinks (to 70%) to stay on one line, else to
 * 62% to stay on two; the subtitle takes up to two lines. contentTop is where the diagram body starts.
 */
export function headerMetrics(preset, title, subtitle) {
  const { width } = PRESETS[preset];
  const margin = marginOf(preset);
  const baseSize = preset === 'slide-16x9' ? 42 : preset === 'social-square' ? 38 : 32;
  const room = width - margin * 2;
  const maxAt = (size) => Math.max(22, Math.floor(room / (size * 0.6)));
  let titleSize = baseSize;
  let titleMax = maxAt(titleSize);
  while (wrapAll(title, titleMax).length > 1 && titleSize > baseSize * 0.7) { titleSize -= 1; titleMax = maxAt(titleSize); }
  if (wrapAll(title, titleMax).length > 1) {
    titleSize = baseSize;
    titleMax = maxAt(titleSize);
    while (wrapAll(title, titleMax).length > 2 && titleSize > baseSize * 0.62) { titleSize -= 1; titleMax = maxAt(titleSize); }
  }
  const titleLines = wrapAll(title, titleMax);
  const titleY = margin + 54;
  const titleLeading = 1.08;
  const titleBottom = titleY + (titleLines.length - 1) * titleSize * titleLeading;
  const subtitleMax = Math.max(30, Math.floor(room / 9));
  const subtitleLines = subtitle ? wrapAll(subtitle, subtitleMax) : [];
  const subtitleY = titleBottom + 30;
  const minTop = preset === 'social-square' ? 166 : 132;
  const contentTop = Math.max(minTop, subtitleLines.length ? subtitleY + (Math.min(subtitleLines.length, 2) - 1) * 20 + 28 : titleBottom + 34);
  return { titleSize, titleMax, titleLines, titleY, titleLeading, subtitleMax, subtitleLines, subtitleY, contentTop, minTop };
}

/** 0 for a compact header (a one-line title and at most one subtitle line), 1 for anything taller. */
export function headerTier(preset, title, subtitle) {
  const m = headerMetrics(preset, String(title ?? ''), String(subtitle ?? ''));
  return m.titleLines.length === 1 && m.subtitleLines.length <= 1 ? 0 : 1;
}

let override = null;
let probe = null;
/** Tuning seam only: replace the committed limits while the quality gate searches for new ones; 'off' disables them (calibration). */
export function setFitLimitsOverride(map) { override = map; }

/** Tuning seam only: observe every (family, kind, size) the validators check. */
export function setFitProbe(fn) { probe = fn; }
export function recordFit(family, kind, size) { if (probe) probe(family, kind, size); }

/** Visual width in cells: CJK, Hangul, fullwidth forms and emoji take two cells, everything else one. */
export function cells(text) {
  let n = 0;
  for (const ch of String(text)) {
    const c = ch.codePointAt(0);
    if ((c >= 0x1100 && c <= 0x115f) || (c >= 0x2e80 && c <= 0xa4cf) || (c >= 0xac00 && c <= 0xd7a3) || (c >= 0xf900 && c <= 0xfaff)
      || (c >= 0xfe30 && c <= 0xfe6f) || (c >= 0xff00 && c <= 0xff60) || (c >= 0xffe0 && c <= 0xffe6) || (c >= 0x1f300 && c <= 0x1faff)) n += 2;
    // Arabic and Hebrew glyph widths depend on the system fallback font, so they are counted with a safety margin.
    else if ((c >= 0x0590 && c <= 0x08ff) || (c >= 0xfb1d && c <= 0xfdff) || (c >= 0xfe70 && c <= 0xfeff)) n += 1.25;
    else n += 1;
  }
  return n;
}

export const PRIMARY = {
  flow: 'nodes', architecture: 'nodes', swot: 'items', quadrant: 'points', comparison: 'columns', timeline: 'items',
  cycle: 'levels', pyramid: 'levels', stack: 'levels', venn: 'sets', sipoc: 'items', raci: 'activities', swimlane: 'lanes',
  fishbone: 'categories', 'journey-map': 'stages', 'capability-map': 'domains', 'strategy-map': 'items',
};

const len = (value) => (Array.isArray(value) ? value.length : undefined);
const widest = (value, keys) => (value && typeof value === 'object' ? Math.max(0, ...keys.map((key) => len(value[key]) ?? 0)) : undefined);

/** The item count that sets how crowded a diagram is (nodes, items, levels...), read defensively from raw data. */
export function primaryCount(family, data) {
  if (!data || typeof data !== 'object') return undefined;
  switch (family) {
    case 'flow': case 'architecture': return len(data.nodes);
    case 'swot': return widest(data, ['strengths', 'weaknesses', 'opportunities', 'threats']);
    case 'quadrant': return len(data.points);
    case 'comparison': return len(data.columns);
    case 'timeline': return len(data.items);
    case 'cycle': case 'pyramid': case 'stack': return len(data.levels ?? data.stages);
    case 'venn': return len(data.sets);
    case 'sipoc': return widest(data, ['suppliers', 'inputs', 'processSteps', 'outputs', 'customers']);
    case 'raci': return len(data.activities);
    case 'swimlane': return len(data.lanes);
    case 'fishbone': return len(data.categories);
    case 'journey-map': return len(data.stages);
    case 'capability-map': return len(data.domains);
    case 'strategy-map': return widest(data, ['financial', 'customer', 'internalProcess', 'learningGrowth']);
    default: return undefined;
  }
}

let context = { preset: 'doc-wide', count: undefined, tier: 1 };
/** Set by validateSpec: the limits depend on the preset, on how many primary items the spec has and on the header height. */
export function setFitContext(preset, count, tier = 1) { context = { preset, count, tier }; }

const decoded = new Map();
function rowsFor(family, preset) {
  const entry = FIT_LIMITS[family];
  const byCount = entry?.rows?.[preset];
  if (!byCount) return null;
  const key = `${family}/${preset}`;
  if (!decoded.has(key)) {
    decoded.set(key, Object.fromEntries(Object.entries(byCount).map(([k, tiers]) => [k, tiers.map((values) => Object.fromEntries(entry.kinds.map((kind, i) => [kind, values[i]])))])));
  }
  return decoded.get(key);
}
function rowAt(family, preset, count) {
  const rows = rowsFor(family, preset);
  if (!rows) return null;
  const ks = Object.keys(rows).map(Number).sort((a, b) => a - b);
  const k = Math.max(ks[0], Math.min(ks.at(-1), count ?? ks.at(-1)));
  const tier = Math.min(context.tier, rows[k].length - 1);
  return { k, max: ks.at(-1), row: rows[k][tier], maxRow: rows[ks.at(-1)][tier], tier };
}

export function lengthLimit(family, kind, fallback) {
  if (override === 'off') return fallback;
  if (override) return override[family]?.lengths?.[kind] ?? fallback;
  return rowAt(family, context.preset, context.count)?.row?.[kind] ?? fallback;
}
export function countLimit(family, kind, fallback) {
  if (override === 'off') return fallback;
  return (override ?? FIT_LIMITS)[family]?.counts?.[kind] ?? fallback;
}
/** Every limit row of a family and preset, keyed by primary count (used by the gate and the docs). */
export function limitRows(family, preset) { return rowsFor(family, preset); }

export function fitMessage(path, family, count, limit, unit = 'characters', kind) {
  if (unit !== 'characters') return `${path} has ${count} items; ${family} diagrams fit at most ${limit}. Split it across two diagrams.`;
  const wide = ' (wide characters such as CJK count double)';
  const at = !override && kind ? rowAt(family, context.preset, context.count) : null;
  if (!at) return `${path} is ${count} characters; ${family} diagrams fit at most ${limit}${wide}. Shorten it or split the diagram.`;
  const noun = PRIMARY[family];
  const more = at.max > at.k && at.maxRow[kind] !== limit ? `; with ${at.max} ${noun}, ${at.maxRow[kind]}` : '';
  return `${path} is ${count} characters; with ${at.k} ${noun} on ${context.preset}${at.tier ? ' and a long title or subtitle' : ''}, ${family} diagrams fit at most ${limit}${more}${wide}. Shorten it or split the diagram.`;
}

const isWide = (ch) => cells(ch) === 2;
/** Longest run of ordinary characters without whitespace; wide (CJK) characters may break anywhere so they end a run. */
export function longestToken(text) {
  let best = 0; let run = 0; let token = ''; let longest = '';
  for (const ch of String(text)) {
    if (/\s/.test(ch) || isWide(ch)) { run = 0; token = ''; continue; }
    run += 1; token += ch;
    if (run > best) { best = run; longest = token; }
    if (ch === '/' || ch === '-' || ch === '\u00b7') { run = 0; token = ''; }
  }
  return { size: best, word: longest };
}

/** Error for a word longer than the family's unbroken-word cap, or null. */
export function tokenProblem(path, family, text) {
  const cap = lengthLimit(family, 'token', Infinity);
  if (cap === Infinity) return null;
  const { size, word } = longestToken(text);
  if (size <= cap) return null;
  return `${path} contains a ${size}-character word ("${word.slice(0, 18)}…"); ${family} diagrams fit words of at most ${cap} characters here. Add spaces or shorten it.`;
}
